### ISSUE TITLE
Importing Files

### ISSUE THREAD

**Issue by JellyMaster125** [GoAnimate-Wrapper/GoAnimate-Assets#1]
I have realized that there has been a new update where there's a UPLOAD A MOVIE button on the home menu now, I tried uploading an audio file, mp4, or an image, but it brought my to this page that said, No webpage was found for the web address: http://goanimate-wrapper.eu-4.evennode.com/upload_movie. Also, I noticed that if I go to the Your Library, it doesn't have an error, and there's a custom backdrop I didn't upload, please tell me how to use this! I also saw a video on the site, and it had custom Street Fighter music!

**Comment by PoleyMagik** [comment]
Hello! I adressed this issue on your comment, but that upload only accepts xmls. There was no custom music, the Street Fighter theme got added. Also, you're posting this on the wrong repo, this is the asset repo.
