### ISSUE TITLE
Do any of you know how to open the swf assets in a decompiler?

### ISSUE THREAD

**Issue by CLarramore** [GoAnimate-Wrapper/GoAnimate-Assets#2]
For some reason when I try to open the SWF assets in a decompiler, it doesn't recognize it as an SWF file. Am I not supposed to use the decompiler?

**Comment by CLarramore** [comment]
Nevermind, I don't need a decompiler.. Since the asset was a sound, I had to requestly the way through to there.

Thanks for the happy bunny theme btw. I'll plan on making these 'voice clips' as sound effects soon.

**Comment by PoleyMagik** [comment]
Hello. GoAnimate assets are encrypted.
